ejercicios = [
    ("My name ___ John.", "is"),
    ("She ___ my sister.", "is"),
    ("We ___ students.", "are"),
    ("He ___ a teacher.", "is"),
    ("They ___ from Spain.", "are"),
    ("It ___ a cat.", "is"),
    ("I ___ hungry.", "am"),
    ("You ___ my friend.", "are"),
    ("She ___ happy.", "is"),
    ("We ___ in the park.", "are"),
    ("My brother ___ tall.", "is"),
    ("He ___ from Italy.", "is"),
    ("It ___ cold today.", "is"),
    ("They ___ at school.", "are"),
    ("My favorite color ___ blue.", "is"),
    ("She ___ a doctor.", "is"),
    ("We ___ in the house.", "are"),
    ("I ___ tired.", "am"),
    ("You ___ my teacher.", "are"),
    ("It ___ a dog.", "is"),
    ("He ___ from Canada.", "is"),
    ("They ___ in the garden.", "are"),
    ("My sister ___ a nurse.", "is"),
    ("She ___ sad.", "is"),
    ("We ___ in the city.", "are"),
    ("My favorite food ___ pizza.", "is"),
    ("He ___ a lawyer.", "is"),
    ("It ___ hot today.", "is"),
    ("They ___ at home.", "are"),
    ("My father ___ a pilot.", "is"),
    ("She ___ angry.", "is"),
    ("I ___ thirsty.", "am"),
    ("You ___ my neighbor.", "are"),
    ("It ___ a bird.", "is"),
    ("He ___ from Mexico.", "is"),
    ("They ___ in the restaurant.", "are"),
    ("My mother ___ a chef.", "is"),
    ("She ___ tired.", "is"),
    ("We ___ in the classroom.", "are"),
    ("My favorite animal ___ cat.", "is"),
    ("He ___ a dentist.", "is"),
    ("It ___ raining outside.", "is"),
    ("They ___ on vacation.", "are"),
    ("My uncle ___ a firefighter.", "is"),
    ("She ___ cold.", "is"),
    ("I ___ happy.", "am"),
    ("You ___ my classmate.", "are"),
    ("It ___ a fish.", "is"),
    ("He ___ from Japan.", "is"),
    ("They ___ in the office.", "are"),
    ("My aunt ___ a police officer.", "is"),
    ("She ___ thirsty.", "is"),
    ("We ___ in the park.", "are"),
    ("My favorite hobby ___ reading.", "is"),
    ("He ___ a scientist.", "is"),
    ("It ___ snowing.", "is"),
    ("They ___ at the beach.", "are"),
    ("My cousin ___ a teacher.", "is"),
    ("She ___ sleepy.", "is"),
    ("I ___ sad.", "am"),
    ("You ___ my friend.", "are"),
    ("It ___ a horse.", "is"),
    ("He ___ from Brazil.", "is"),
    ("They ___ in the mountains.", "are"),
    ("My grandfather ___ a farmer.", "is"),
    ("She ___ happy.", "is"),
    ("We ___ in the forest.", "are"),
    ("My favorite sport ___ soccer.", "is"),
    ("He ___ an engineer.", "is"),
    ("It ___ windy.", "is"),
    ("They ___ in the countryside.", "are"),
    ("My grandmother ___ a baker.", "is"),
    ("She ___ thirsty.", "is"),
    ("I ___ excited.", "am"),
    ("You ___ my roommate.", "are"),
    ("It ___ a rabbit.", "is"),
    ("He ___ from Australia.", "is"),
    ("They ___ in the desert.", "are"),
    ("My sister ___ a musician.", "is"),
    ("She ___ sleepy.", "is"),
    ("I ___ hungry.", "am"),
    ("You ___ my colleague.", "are"),
    ("It ___ a turtle.", "is"),
    ("He ___ from China.", "is"),
    ("They ___ in the countryside.", "are"),
    ("My mother ___ a singer.", "is"),
    ("She ___ cold.", "is"),
    ("We ___ at the lake.", "are"),
    ("My favorite movie ___ Titanic.", "is"),
    ("He ___ a photographer.", "is"),
    ("It ___ cloudy.", "is"),
    ("They ___ in the park.", "are"),
    ("My father ___ a writer.", "is")
]